name: styled_text
description: Text widget with formatting via tags. Makes it easier to use formatted text in multilingual applications.
version: 1.0.1+1
author: Andy Chentsov <chentsov@gmail.com>
homepage: https://github.com/andyduke/styled_text_package/tree/master/styled_text
repository: https://github.com/andyduke/styled_text_package
issue_tracker: https://github.com/andyduke/styled_text_package/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xmlstream: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
